name: Landbound
version: '1.0-SNAPSHOT'
main: me.kezer0.landbound.Landbound
api-version: '1.21'
authors: [ kezer0 ]
commands:
  land:
    description: "teleports you to your land"
    usage: "/land <config>"
    aliases: [1]
    permission: "permission.node"
    permission-message: "You do not have permission to use this command"
  hub:
    description: "teleports you to hub"
    usage: "/hub"
    permission: "permission.node"
    permission-message: "You do not have permission to use this command"
  debugitem:
    description: "teleports you to hub"
    usage: "/debugitem <args>"
    permission: "permission.node"
    permission-message: "You do not have permission to use this command"
  testitem:
    description: "teleports you to hub"
    usage: "/testitem"
    permission: "permission.node"
    permission-message: "You do not have permission to use this command"
  entity:
    description: "entity"
    usage: "/entity"
    permission: "permission.node"
    permission-message: "You do not have permission to use this command"


